# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.5
    hooks:
      # 檢查 lockfile 是否為最新狀態
      - id: uv-lock
      # 自動翻新 requirements.txt
      - id: uv-export
        args: ["--no-hashes", "--frozen", "--format", "requirements-txt", "-o=requirements.txt"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      # Linter 修正
      - id: ruff
        args: ["--fix"]
      # Formatter 修正
      - id: ruff-format
