@set "TEST_RESULTS_DIR=%1"
@rmdir /s /q "%TEST_RESULTS_DIR%\test_pdf_to_img"
@rmdir /s /q "%TEST_RESULTS_DIR%\test_img_to_pdf"
@rmdir /s /q "%TEST_RESULTS_DIR%\test_pdf_split"
@rmdir /s /q "%TEST_RESULTS_DIR%\test_pdf_merge"
@rmdir /s /q "%TEST_RESULTS_DIR%\test_pdf_to_img_mp"
@rmdir /s /q "%TEST_RESULTS_DIR%\test_pdf_to_img_mp_single"
@mkdir "%TEST_RESULTS_DIR%\test_pdf_to_img"
@mkdir "%TEST_RESULTS_DIR%\test_img_to_pdf"
@mkdir "%TEST_RESULTS_DIR%\test_pdf_split"
@mkdir "%TEST_RESULTS_DIR%\test_pdf_merge"
@mkdir "%TEST_RESULTS_DIR%\test_pdf_to_img_mp"
@mkdir "%TEST_RESULTS_DIR%\test_pdf_to_img_mp_single"